const fallbackWines=[
{slug:'santa-julia-chenin-dulce',winery:'Santa Julia',name:'Dulce Natural Chenin',region:'Mendoza, Argentina',grapes:['Chenin Blanc'],type:'Sobremesa',price:89.9,featured:true},
{slug:'dv-catena-chardonnay',winery:'D.V. Catena',name:'Chardonnay - Chardonnay',region:'Mendoza, Argentina',grapes:['Chardonnay'],type:'Branco',price:179.9,featured:true},
{slug:'dv-catena-malbec',winery:'D.V. Catena',name:'Malbec - Malbec',region:'Mendoza, Argentina',grapes:['Malbec'],type:'Tinto',price:189.9,featured:true},
{slug:'santa-julia-organica-malbec',winery:'Santa Julia',name:'Orgánica Malbec',region:'Mendoza, Argentina',grapes:['Malbec'],type:'Tinto',price:99.9,featured:true},
{slug:'catena-malbec',winery:'Catena Zapata',name:'Malbec',region:'Mendoza, Argentina',grapes:['Malbec'],type:'Tinto',price:159.9,featured:true}
];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=n=>'R$ '+Number(n||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
function productCard(w){const img=w.image_url?'<img src="'+esc(w.image_url)+'" alt="'+esc(w.name)+'">':'<div class="bottle-fallback"></div>';return '<article class="product-card"><a href="/vinho.html?slug='+encodeURIComponent(w.slug)+'"><div class="product-image">'+img+'</div><div class="product-meta"><small>'+esc(w.winery||'Videira')+'</small><h3>'+esc(w.name)+'</h3><div class="product-sub">'+esc(w.region||'')+'</div><div class="product-price">'+money(w.price)+'</div></div></a><div class="product-actions"><button class="quote-btn" data-slug="'+esc(w.slug)+'">Pedir orçamento</button><button class="save-btn" aria-label="Adicionar">+</button></div></article>'}
function setupCarousel(root){if(!root)return;const rail=root.querySelector('.product-rail,.grape-rail');if(!rail)return;root.querySelector('.prev')?.addEventListener('click',()=>rail.scrollBy({left:-520,behavior:'smooth'}));root.querySelector('.next')?.addEventListener('click',()=>rail.scrollBy({left:520,behavior:'smooth'}));let down=false,start=0,left=0,moved=false;rail.addEventListener('pointerdown',e=>{down=true;moved=false;start=e.clientX;left=rail.scrollLeft});rail.addEventListener('pointermove',e=>{if(!down)return;const delta=e.clientX-start;if(Math.abs(delta)>6)moved=true;if(moved){e.preventDefault();rail.scrollLeft=left-delta}});rail.addEventListener('pointerup',()=>{down=false;setTimeout(()=>moved=false,0)});rail.addEventListener('pointercancel',()=>{down=false;moved=false});rail.addEventListener('pointerleave',()=>{down=false});rail.addEventListener('click',e=>{if(moved){e.preventDefault();e.stopPropagation()}})}
(async()=>{
const db=window.videiraDb;let wines=fallbackWines,types=[],grapes=[],wineries=[];
if(db){const [wr,tr,gr,br]=await Promise.all([db.from('wines').select('*').eq('active',true).order('sort_order'),db.from('wine_types_catalog').select('*').eq('active',true).order('sort_order'),db.from('grapes_catalog').select('*').eq('active',true).order('sort_order'),db.from('bodegas').select('*').eq('active',true).order('sort_order')]);if(wr.data?.length)wines=wr.data;types=tr.data||[];grapes=gr.data||[];wineries=br.data||[]}
window.__VIDEIRA_WINES=wines;
const featured=document.getElementById('featuredRail');if(featured)featured.innerHTML=(wines.filter(x=>x.featured).length?wines.filter(x=>x.featured):wines).map(productCard).join('');
const typeGrid=document.getElementById('typeGrid');if(typeGrid){if(!types.length)types=[{name:'Tinto',description:'Intensos e elegantes'},{name:'Branco',description:'Frescos e aromáticos'},{name:'Rosé',description:'Leves e versáteis'},{name:'Espumante',description:'Para celebrar'},{name:'Frizante',description:'Leves e descontraídos'},{name:'Sobremesa',description:'Doces e envolventes'}];typeGrid.innerHTML=types.slice(0,6).map((t,i)=>'<a class="type-card" href="/loja.html?tipo='+encodeURIComponent(t.name)+'"><div class="type-art"'+(t.image_url?' style="background-image:url('+JSON.stringify(t.image_url)+')"':'')+'></div><strong>'+esc(t.name)+'</strong><small>'+esc(t.description||'')+'</small></a>').join('')}
const grapeRail=document.getElementById('grapeRail');if(grapeRail){if(!grapes.length)grapes=[{name:'Malbec',description:'Frutado, macio e intenso.'},{name:'Chardonnay',description:'Versátil, fresco e elegante.'},{name:'Chenin Blanc',description:'Aromático, fresco e versátil.'},{name:'Cabernet Franc',description:'Elegante, herbal e vibrante.'},{name:'Pinot Noir',description:'Delicado e perfumado.'},{name:'Merlot',description:'Macio e redondo.'}];grapeRail.innerHTML=grapes.map(g=>'<a class="grape-card" href="/loja.html?uva='+encodeURIComponent(g.name)+'"><div class="grape-art"'+(g.image_url?' style="background-image:url('+JSON.stringify(g.image_url)+')"':'')+'></div><div class="grape-body"><h3>'+esc(g.name)+'</h3><p>'+esc(g.description||'Explore os rótulos desta variedade.')+'</p><b>Ver vinhos</b></div></a>').join('')}
const homeWineries=document.getElementById('homeWineries');if(homeWineries){if(!wineries.length)wineries=[{name:'Santa Julia',country:'Argentina',description:'Tradição e inovação em Mendoza.'},{name:'Catena Zapata',country:'Argentina',description:'Altitude e expressão de terroir.'},{name:'Garzón',country:'Uruguai',description:'Elegância atlântica e identidade uruguaia.'}];const stock=['https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1464638681273-096c166ab676?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1473973266408-ed4e27abdd47?auto=format&fit=crop&w=900&q=85'];homeWineries.innerHTML=wineries.slice(0,3).map((w,i)=>'<a class="winery-card" href="/loja.html?vinicola='+encodeURIComponent(w.name)+'" style="background-image:url('+JSON.stringify(w.image_url||stock[i%3])+')"><div><span>'+esc(w.country||'')+'</span><h3>'+esc(w.name)+'</h3><p>'+esc(w.description||'Conheça os vinhos desta vinícola.')+'</p><b>Conhecer</b></div></a>').join('')}
document.querySelectorAll('.carousel-shell').forEach(setupCarousel);
const catalog=document.getElementById('catalog');if(catalog){const typeFilters=document.getElementById('typeFilters');if(typeFilters){const names=[...new Set(wines.map(w=>w.type).filter(Boolean))];typeFilters.innerHTML=names.map(n=>'<label><input type="checkbox" value="'+esc(n)+'"> '+esc(n)+'</label>').join('')}const qs=new URLSearchParams(location.search);function filtered(){let list=[...wines];const q=(qs.get('q')||'').toLowerCase();if(q)list=list.filter(w=>[w.name,w.winery,w.region,w.type,(w.grapes||[]).join(' ')].join(' ').toLowerCase().includes(q));const selected=[...document.querySelectorAll('#typeFilters input:checked')].map(x=>x.value);if(selected.length)list=list.filter(w=>selected.includes(w.type));const max=Number(document.getElementById('priceRange')?.value||99999);list=list.filter(w=>!w.price||Number(w.price)<=max);const g=(document.getElementById('grapeSearch')?.value||'').toLowerCase();if(g)list=list.filter(w=>(w.grapes||[]).join(' ').toLowerCase().includes(g));const sort=document.getElementById('sort')?.value;if(sort==='Menor preço')list.sort((a,b)=>a.price-b.price);if(sort==='Maior preço')list.sort((a,b)=>b.price-a.price);return list}function renderCatalog(){const list=filtered();catalog.innerHTML=list.map(productCard).join('');document.getElementById('resultCount').textContent=list.length+' vinhos encontrados'}document.querySelectorAll('#filters input,#sort').forEach(x=>x.addEventListener('input',()=>{if(x.id==='priceRange')document.getElementById('priceValue').textContent='Até '+money(x.value);renderCatalog()}));document.getElementById('clearFilters')?.addEventListener('click',()=>{document.querySelectorAll('#filters input[type=checkbox]').forEach(x=>x.checked=false);document.getElementById('grapeSearch').value='';document.getElementById('priceRange').value=1000;renderCatalog()});document.getElementById('filterToggle')?.addEventListener('click',()=>document.getElementById('filters').classList.toggle('open'));renderCatalog()}
const product=document.getElementById('product');if(product){const slug=new URLSearchParams(location.search).get('slug')||wines[0]?.slug;const w=wines.find(x=>x.slug===slug)||wines[0];if(w){document.title=w.name+' | Videira';document.getElementById('crumbWine').textContent=w.name;const img=w.image_url?'<img src="'+esc(w.image_url)+'" alt="'+esc(w.name)+'">':'<div class="detail-bottle"><span>'+esc(w.winery)+'</span></div>';product.innerHTML='<div class="product-detail"><div class="product-gallery">'+img+'</div><div class="product-info"><span class="winery">'+esc(w.winery)+'</span><h1>'+esc(w.name)+'</h1><div class="region">'+esc(w.region||'')+'</div><div class="facts"><div><b>Tipo</b><span>'+esc(w.type||'')+'</span></div><div><b>Uva</b><span>'+esc((w.grapes||[]).join(', '))+'</span></div><div><b>Região</b><span>'+esc(w.region||'')+'</span></div><div><b>Produtor</b><span>'+esc(w.winery||'')+'</span></div></div><p class="description">'+esc(w.description||'Consulte disponibilidade, safra e condições comerciais no orçamento.')+'</p><div class="detail-price">'+money(w.price)+'</div><button class="detail-quote quote-btn" data-slug="'+esc(w.slug)+'">Pedir orçamento</button></div></div>';const same=document.getElementById('same');if(same)same.innerHTML=wines.filter(x=>x.slug!==w.slug).slice(0,8).map(productCard).join('')}}
const explore=document.getElementById('exploreGrid');if(explore){const kind=document.querySelector('.explore-page')?.dataset.kind;let data=[];if(kind==='grapes')data=grapes;if(kind==='wineries')data=wineries;if(kind==='regions'){const map=new Map();wines.forEach(w=>{if(w.region&&!map.has(w.region))map.set(w.region,{name:w.region,description:w.country||''})});data=[...map.values()]}const stock=['https://images.unsplash.com/photo-1537640538966-79f369143f8f?auto=format&fit=crop&w=800&q=80','https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=800&q=80','https://images.unsplash.com/photo-1464638681273-096c166ab676?auto=format&fit=crop&w=800&q=80'];function draw(list){explore.innerHTML=list.map((x,i)=>'<a class="explore-card" href="/loja.html"><div class="explore-visual" style="background-image:url('+JSON.stringify(x.image_url||stock[i%3])+')"></div><div class="explore-body"><h3>'+esc(x.name)+'</h3><p>'+esc(x.description||x.region||'Explore os rótulos relacionados.')+'</p><b>Ver rótulos</b></div></a>').join('')}draw(data);document.getElementById('exploreSearch')?.addEventListener('input',e=>draw(data.filter(x=>String(x.name).toLowerCase().includes(e.target.value.toLowerCase()))))}
document.addEventListener('click',e=>{const a=e.target.closest('.product-card a[href]');if(a&&!e.defaultPrevented){const href=a.getAttribute('href');if(href){e.preventDefault();window.location.href=href;return}}});
document.addEventListener('click',e=>{const b=e.target.closest('.quote-btn');if(!b)return;const w=wines.find(x=>x.slug===b.dataset.slug);if(!w)return;const wa=(window.__VIDEIRA_SETTINGS?.whatsapp||'').replace(/\D/g,'');const msg=encodeURIComponent('Olá! Gostaria de solicitar um orçamento para '+w.winery+' '+w.name+'.');window.open(wa?'https://wa.me/'+wa+'?text='+msg:'https://wa.me/?text='+msg,'_blank','noopener')});
})();